### ISSUE TITLE
Sandbox NAT instance size is too small to run Bro

### ISSUE THREAD

**Issue by gene1wood** [nubisproject/nubis-nat#175] opened 2017-03-23 17:06 UTC
The current [NAT instance size in sandbox](https://github.com/nubisproject/nubis-nat/blob/334768905667509fd3748d4b9dad9787359f258a/nubis/cloudformation/main.json#L46-L48) is `t2.small` which doesn't have enough memory to run Bro and results in Bro crashes and Bro crash alerts (sent currently to infosec, though that's being fixed in nubisproject/nubis-puppet-nsm#12

Please increase this instance size to prevent Bro from crashing. You may want to try a few instance sizes to find out what the smallest is that can run Bro without running out of memory.

**Comment by gene1wood** [comment] 2017-03-23 17:07
@michalpurzynski Here's the ticket on the Bro instance size

**Comment by limed** [comment] 2017-10-11 18:41
Dupe of nubisproject/nubis-deploy#81 we will be fixing this issue there

**Closed by limed** 2017-10-11 18:41 UTC
Labels: duplicate
